### ISSUE TITLE
Halloween skyboxes not showing up in non-halloween maps

### ISSUE THREAD

**Issue by Sharkmaw** [Jugheadbomb/SM-TF2Halloween#1]
Tested on a server with latest build of sourcemod and no other plugins but the dependencies. Everything else works great.

**Comment by Jugheadbomb** [comment]
Could you please tell map name? Would be interesting for me to test this, because everything is working for me.

**Comment by Sharkmaw** [comment]
Was all non-halloween maps for me. I'll likely attempt a clean server installation at some point and inform you about whether it resolves the issue. I'll then either close the problem if it's fixed or let you know if the problem persists.
